// Auto-generated vehicle models database
// Compiled from NHTSA API & fallback definitions
// Total Makes: 66

export const allVehiclesModels: Record<string, string[]> = {
    "Acura": [
        "ADX",
        "CL",
        "ILX",
        "Integra",
        "Legend",
        "MDX",
        "NSX",
        "RDX",
        "RL",
        "RLX",
        "RSX",
        "SLX",
        "TL",
        "TLX",
        "TSX",
        "Vigor",
        "ZDX"
    ],
    "Alfa Romeo": [
        "164",
        "4C",
        "8C Competizione Spider",
        "GTV",
        "GTV6",
        "Giulia",
        "Giulia (952)",
        "Milano",
        "Spider",
        "Stelvio",
        "Tonale"
    ],
    "Aston Martin": [
        "DB11",
        "DB12",
        "DB7",
        "DB9",
        "DBS",
        "DBX",
        "Lagonda",
        "Rapide",
        "V12 Vantage",
        "V8",
        "V8 Vantage",
        "Valhalla",
        "Valiant",
        "Valour",
        "Vanquish",
        "Vanquish Zagato",
        "Vantage",
        "Virage"
    ],
    "Audi": [
        "100",
        "200",
        "4000",
        "5000",
        "80",
        "90",
        "A3",
        "A4",
        "A4 allroad",
        "A5",
        "A6",
        "A6 allroad",
        "A7",
        "A7 e",
        "A8",
        "A8 L",
        "A8 L e",
        "A8 e",
        "Cabriolet",
        "Coupe",
        "Q3",
        "Q4",
        "Q4 e-tron",
        "Q5",
        "Q5 e",
        "Q6",
        "Q7",
        "Q8",
        "Quattro",
        "R8",
        "RS 3",
        "RS 4",
        "RS 5",
        "RS 6",
        "RS 6 Avant",
        "RS 7",
        "RS Q8",
        "RS e-tron GT",
        "RS3",
        "RS5",
        "RS6",
        "RS7",
        "S e-tron GT",
        "S3",
        "S4",
        "S5",
        "S6",
        "S7",
        "S8",
        "SQ5",
        "SQ6",
        "SQ7",
        "SQ8",
        "TT",
        "TT RS",
        "TTS",
        "V8",
        "allroad",
        "e-tron",
        "e-tron GT",
        "e-tron Sportback"
    ],
    "Bentley": [
        "A Smith GT Bentley",
        "ARMOURED ARNAGE",
        "Arnage",
        "Azure",
        "Bentayga",
        "Bentley Industries, LLC",
        "Bentley Trailers & Custom Coaches",
        "Brooklands",
        "Continental",
        "Continental GT",
        "Eight",
        "Flying Spur",
        "Mulsanne",
        "Roll Royce Silver Seraph",
        "Rolls-Royce Park Ward",
        "Turbo"
    ],
    "BMW": [
        "128i",
        "135i",
        "1M",
        "2 Series",
        "228",
        "228i",
        "230i",
        "3 Series",
        "318i",
        "318iC",
        "318iS",
        "318ti",
        "320i",
        "323i",
        "323iC",
        "323is",
        "325/325e",
        "325/325eS",
        "325Ci",
        "325i",
        "325i/325is",
        "325iC",
        "325iS",
        "325ix",
        "325xi",
        "328Ci",
        "328d",
        "328i",
        "328iC",
        "328iS",
        "328xi",
        "330Ci",
        "330e",
        "330i",
        "330xi",
        "335",
        "335d",
        "335i",
        "335is",
        "335xi",
        "340i",
        "4 Series",
        "428i",
        "430i",
        "435i",
        "440i",
        "5 Series",
        "524td",
        "525i",
        "525iA",
        "525xi",
        "528e",
        "528i",
        "528xi",
        "530e",
        "530i",
        "530iA",
        "530xi",
        "533i",
        "535d",
        "535i",
        "535i/535is",
        "535xi",
        "540d",
        "540i",
        "540iA",
        "545i",
        "550e",
        "550i",
        "633 csi",
        "635CSi",
        "640i",
        "640xi",
        "645Ci",
        "645i",
        "650i",
        "650i, Alpina B6",
        "650i, B6",
        "650xi",
        "7 Series",
        "730i",
        "733i",
        "735i",
        "735iL",
        "740Li",
        "740e",
        "740i",
        "740iL",
        "745Le",
        "745Li",
        "745e",
        "745i",
        "750Li",
        "750Li, Alpina B7",
        "750Lxi",
        "750Lxi, Alpina B7",
        "750e",
        "750i",
        "750i, Alpina B7",
        "750i, B7",
        "750iL",
        "750xi",
        "750xi, Alpina B7",
        "760Li",
        "760i",
        "8 Series",
        "840Ci",
        "840i",
        "850CSi",
        "850Ci",
        "850i",
        "ActiveE",
        "ActiveHybrid 3",
        "ActiveHybrid 5",
        "ActiveHybrid 7",
        "Alpina",
        "Alpina B8",
        "B7",
        "C 400 GT",
        "C 400 X",
        "C 600",
        "C 650",
        "C 650 GT",
        "C Evolution",
        "CE 02",
        "CE 04",
        "F 650",
        "F 650 CS",
        "F 650 GS",
        "F 650 S",
        "F 700 GS",
        "F 750 GS",
        "F 800 GS",
        "F 800 GT",
        "F 800 R",
        "F 800 S",
        "F 800 ST",
        "F 850 GS",
        "F 900",
        "F 900 GS",
        "F 900 GS Adventure",
        "F 900 GS-P",
        "F 900 R",
        "F 900 XR",
        "G 310 GS",
        "G 310 R",
        "G 450 X",
        "G 650",
        "G 650 GS",
        "HP2",
        "HP4",
        "K 100 LT",
        "K 100 RS",
        "K 100 RT",
        "K 1100 LT",
        "K 1100 RS",
        "K 1200 GT",
        "K 1200 LT",
        "K 1200 R",
        "K 1200 RS",
        "K 1200 S",
        "K 1300 GT",
        "K 1300 R",
        "K 1300 S",
        "K 1600 B",
        "K 1600 GT",
        "K 1600 GTL",
        "K1",
        "K100",
        "K75",
        "K75RT",
        "K75S",
        "L7",
        "M 1000",
        "M 1000 R",
        "M 1000 RR",
        "M 1000 XR",
        "M2",
        "M235",
        "M235i",
        "M240i",
        "M3",
        "M3 E30",
        "M3 E46",
        "M3 E92",
        "M340i",
        "M3Ci",
        "M4",
        "M440i",
        "M5",
        "M5 E39",
        "M550i",
        "M6",
        "M760Li",
        "M760i",
        "M8",
        "M850i",
        "R 100",
        "R 100 CS",
        "R 100 GS",
        "R 100 GSPD",
        "R 100 R",
        "R 100 RS",
        "R 100 RT",
        "R 1100 GS",
        "R 1100 R",
        "R 1100 RS",
        "R 1100 RT",
        "R 1100 S",
        "R 1150 GS",
        "R 1150 R",
        "R 1150 RS",
        "R 1150 RT",
        "R 12",
        "R 12 G/S",
        "R 12 nineT",
        "R 1200 C",
        "R 1200 CL",
        "R 1200 GS",
        "R 1200 R",
        "R 1200 RS",
        "R 1200 RT",
        "R 1200 S",
        "R 1200 ST",
        "R 1250 GS",
        "R 1250 GS Adventure",
        "R 1250 R",
        "R 1250 RS",
        "R 1250 RT",
        "R 1300 GS",
        "R 1300 GS Adventure",
        "R 1300 R",
        "R 1300 RS",
        "R 1300 RT",
        "R 18",
        "R 18 B",
        "R 18 Classic",
        "R 18 Roctane",
        "R 18 Transcontinental",
        "R 65",
        "R 65 LS",
        "R 80",
        "R 80 GS",
        "R 80 RT",
        "R 80 ST",
        "R 850 R",
        "R 900 RT",
        "R nineT",
        "S 1000 R",
        "S 1000 RR",
        "S 1000 XR",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "XM",
        "Z3",
        "Z4",
        "Z8",
        "i3",
        "i4",
        "i5",
        "i7",
        "i8",
        "iX"
    ],
    "Bugatti": [
        "Chiron",
        "Chiron Pur Sport",
        "Chiron Supersport",
        "Divo",
        "EB110",
        "Mistral",
        "Veyron"
    ],
    "Buick": [
        "Allure",
        "Cascada",
        "Century",
        "Coachbuilder",
        "Electra",
        "Enclave",
        "Encore",
        "Encore GX",
        "Envision",
        "Envista",
        "GNX",
        "Grand National",
        "Incomplete",
        "LaCrosse",
        "LeSabre",
        "Lucerne",
        "Park Avenue",
        "Rainier",
        "Reatta",
        "Regal",
        "Regal TourX",
        "Rendezvous",
        "Riviera",
        "Roadmaster",
        "Skyhawk",
        "Skylark",
        "Somerset",
        "Terraza",
        "Verano"
    ],
    "Cadillac": [
        "60 Special",
        "ATS",
        "Allante",
        "Armored Vehicle",
        "Brougham",
        "CT4",
        "CT5",
        "CT6",
        "CTS",
        "Catera",
        "Celestiq",
        "Cimarron",
        "Commercial Chassis",
        "DTS",
        "DeVille",
        "Deville",
        "ELR",
        "Eldorado",
        "Escalade",
        "Escalade ESV",
        "Escalade IQ",
        "Escalade IQL",
        "Fleetwood",
        "Funeral Coach",
        "Hearse",
        "Limousine",
        "Lyriq",
        "Optiq",
        "SRX",
        "STS",
        "Seville",
        "Stretch Limousine",
        "Vistiq",
        "XLR",
        "XT4",
        "XT5",
        "XT6",
        "XTS"
    ],
    "Chevrolet": [
        "3 ton",
        "3500",
        "3500/4500",
        "3500HD",
        "3500HG",
        "4500",
        "4500HD",
        "4500HG",
        "4500XD",
        "5500HD",
        "5500HG",
        "5500XD",
        "5500XG",
        "6500XD",
        "7500XD",
        "Alero",
        "Aluminum Tilt",
        "Astro Van",
        "Avalanche",
        "Aveo",
        "B7",
        "Bel Air",
        "Beretta",
        "Blazer",
        "Bolt",
        "Bolt EUV",
        "Bolt EV",
        "Bolt Incomplete",
        "BrightDrop",
        "Bus Chassis",
        "C/K Pickup",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "Camaro",
        "Caprice",
        "Caprice Police Vehicle",
        "Captiva Sport",
        "Cavalier",
        "Celebrity",
        "Chevelle",
        "Chevette",
        "Citation",
        "City Express",
        "Cobalt",
        "Colorado",
        "Corsica",
        "Corvette",
        "Corvette C5",
        "Corvette C6",
        "Corvette C7",
        "Corvette C8",
        "Corvette ZR1",
        "Cruze",
        "Cruze Limited",
        "Cutaway Chassis",
        "Cutaway Van",
        "D7",
        "El Camino",
        "Epica",
        "Equinox",
        "Express",
        "FTR / 6500XD",
        "Forward Control",
        "G-Series",
        "GMT-400",
        "Geo Prizm",
        "Geo Spectrum",
        "Geo Sprint",
        "HHR",
        "Hearse/Limo",
        "Hearse/Limo Commercial Chassis",
        "Heavy Conventional",
        "Hi-Cube",
        "Impala",
        "Impala Limited",
        "K5 Blazer",
        "Kalos",
        "LUV",
        "Lumina",
        "Lumina APV",
        "Malibu",
        "Malibu Classic",
        "Malibu Limited",
        "Matiz",
        "Metro",
        "Military Truck",
        "Monte Carlo",
        "Motorhome Chassis",
        "Nova",
        "Onix",
        "Optra",
        "Orlando",
        "P - Series",
        "P Truck Forward",
        "P6S",
        "R Conventional",
        "S-10 Blazer",
        "S-10 Pickup",
        "S6",
        "S7",
        "SS",
        "SSR",
        "Silverado",
        "Silverado 1500",
        "Silverado 2500 HD",
        "Silverado 3500 HD",
        "Silverado HD",
        "Silverado LD",
        "Silverado LTD",
        "Sonic",
        "Spark",
        "Suburban",
        "Suburban HD",
        "T-Series",
        "Tahoe",
        "Tracker",
        "Trailblazer",
        "Traverse",
        "Traverse Limited",
        "Trax",
        "U100",
        "Uplander",
        "V Conventional",
        "Venture",
        "Volt",
        "W3",
        "W3500/W4500",
        "W4",
        "W5",
        "W5500/W5500 HD",
        "W6",
        "W7"
    ],
    "Chrysler": [
        "200",
        "300",
        "300C",
        "Aspen",
        "Caravan",
        "Cirrus",
        "Concorde",
        "Concorde/LHS",
        "Conquest",
        "Cordoba",
        "Crossfire",
        "Daytona",
        "Dynasty",
        "E-CLASS",
        "EXECUTIVE",
        "FIFTH AVENUE",
        "Grand Caravan",
        "Grand Voyager",
        "Imperial",
        "Intrepid",
        "LHS",
        "Laser",
        "LeBaron",
        "NEWPORT",
        "Neon",
        "New Yorker",
        "PT Cruiser",
        "Pacifica",
        "Prowler",
        "SALON",
        "Sebring",
        "Shadow",
        "Stratus",
        "TC",
        "Town and Country",
        "Viper",
        "Vision",
        "Voyager"
    ],
    "Dodge": [
        "400",
        "480 Series",
        "580 Series",
        "600",
        "ARIES",
        "Avenger",
        "Caliber",
        "Caravan",
        "Caravan/Grand Caravan",
        "Challenger",
        "Charger",
        "Chassis with Powertrain",
        "Colt",
        "Conquest",
        "D-Series",
        "D50",
        "DIPLOMAT",
        "Dakota",
        "Dart",
        "Daytona",
        "Dodgen Industries",
        "Durango",
        "Dynasty",
        "Grand Caravan",
        "Hornet",
        "Intrepid",
        "Journey",
        "LANCER",
        "Magnum",
        "Mini Ram",
        "Mirada",
        "Monaco",
        "Neon",
        "Neon SRT-4",
        "Nitro",
        "OMNI",
        "RAM 50",
        "RD200 / RD250",
        "Raider",
        "Ram",
        "Ram Chassis Cab",
        "Ram SRT-10",
        "Ram Van",
        "Ram Wagon",
        "Ramcharger",
        "Rampage",
        "Royal Mini Ram Van",
        "ST.REGIS",
        "Shadow",
        "Shelby Charger",
        "Spirit",
        "Sprinter",
        "Stealth",
        "Stratus",
        "Viper",
        "W-Series"
    ],
    "Ferrari": [
        "12Cilindri",
        "296",
        "296 Speciale",
        "296 Speciale A",
        "3.2 Mondial",
        "308 Convertible",
        "308GTB",
        "308GTB Quattrovalvole",
        "308GTBi",
        "308GTS",
        "308GTS Quattrovalvole",
        "308GTSi",
        "328",
        "328 GTB",
        "328 GTS",
        "348 Spider",
        "348 tb",
        "348 ts",
        "355 Berlinetta",
        "355 GTS",
        "355 Spider",
        "360",
        "360 Modena",
        "430",
        "456",
        "456M",
        "458",
        "458 Italia",
        "488",
        "512 TR",
        "550 Barchetta",
        "550 Maranello",
        "575M Maranello",
        "599",
        "599 GTB",
        "599 GTB Fiorano",
        "612 Scaglietti",
        "812",
        "California",
        "California T",
        "Challenge Stradale",
        "Daytona SP3",
        "Enzo",
        "F12",
        "F12 Berlinetta",
        "F12 Special Series",
        "F12 tdf (Tour de France)",
        "F355",
        "F40",
        "F430",
        "F50",
        "F60 America",
        "F8",
        "F80",
        "FF",
        "Ferrari 849 Testarossa",
        "GTC4Lusso",
        "La Ferrari",
        "LaFerrari",
        "Mondial 8",
        "Mondial T",
        "Monza SP1/SP2",
        "Portofino",
        "Portofino M",
        "Purosangue",
        "Roma",
        "SF90",
        "Stradale",
        "Testarossa"
    ],
    "Fiat": [
        "124 Spider",
        "500",
        "500L",
        "500X",
        "500e",
        "Barchetta",
        "Brava",
        "Ducato",
        "Freemont",
        "Spider 2000",
        "Strada",
        "X 1/9"
    ],
    "Fisker": [
        "Karma",
        "Nina",
        "Ocean"
    ],
    "Ford": [
        "'34",
        "1500 Foldaway",
        "A8513",
        "A9513",
        "A9522",
        "AT8513",
        "AT9513",
        "AT9522",
        "Aerostar",
        "Affordable Aluminum",
        "Affordable Trailers",
        "Aspire",
        "B-750",
        "B600",
        "B6000",
        "B700",
        "B7000",
        "B800",
        "Bradford #1",
        "Bradford Built",
        "Bronco",
        "Bronco II",
        "Bronco Raptor",
        "Bronco Sport",
        "C-Max",
        "C600",
        "C700",
        "C7000",
        "C800",
        "C8000",
        "CF6000",
        "CF7000",
        "CF8000",
        "CFT8000",
        "CL9000",
        "CLT9000",
        "CRANFORD RADIATOR INC.",
        "CT800",
        "CT8000",
        "Classic Sedan",
        "Commercial Chassis",
        "Contour",
        "Cordova Sedan",
        "Courier",
        "Crown Victoria",
        "E-100",
        "E-150",
        "E-250",
        "E-350",
        "E-450",
        "E-550",
        "Eagle Ford Tanks & Trailers LLC",
        "EcoSport",
        "Ecosport",
        "Edge",
        "Escape",
        "Escort",
        "Escort RS Cosworth",
        "Excursion",
        "Expedition",
        "Expedition EL",
        "Expedition MAX",
        "Expedition Max",
        "Explorer",
        "Explorer Sport",
        "Explorer Sport Trac",
        "F-100",
        "F-150",
        "F-150 Heritage",
        "F-150 Lightning",
        "F-150 Raptor",
        "F-250",
        "F-250 Super Duty",
        "F-350",
        "F-350 Super Duty",
        "F-450",
        "F-450 Super Duty",
        "F-550",
        "F-590",
        "F-600",
        "F-650",
        "F-700",
        "F-750",
        "F-800",
        "F-Super Duty",
        "F6000",
        "F7000",
        "F8000",
        "FT800",
        "FT8000",
        "FT900",
        "Fairmont",
        "Falcon",
        "Festiva",
        "Fiesta",
        "Five Hundred",
        "Flex",
        "Focus",
        "Ford GT",
        "Fords Trailer Sales",
        "Freestar",
        "Freestyle",
        "Fusion",
        "GT",
        "GT MKII",
        "Granada",
        "L800",
        "L8000",
        "L8501",
        "L8511",
        "L8513",
        "L9000",
        "L9501",
        "L9511",
        "L9513",
        "L9522",
        "LA8000",
        "LA9000",
        "LL9000",
        "LLA9000",
        "LLS9000",
        "LN600",
        "LN700",
        "LN7000",
        "LN800",
        "LN8000",
        "LN9000",
        "LNT800",
        "LNT8000",
        "LNT9000",
        "LS8000",
        "LS9000",
        "LT800",
        "LT8000",
        "LT8501",
        "LT8511",
        "LT8513",
        "LT9000",
        "LT9501",
        "LT9511",
        "LT9513",
        "LT9522",
        "LTA9000",
        "LTD",
        "LTL9000",
        "LTLA9000",
        "LTLS9000",
        "LTS8000",
        "LTS9000",
        "Laser",
        "Low Cab Forward",
        "Lyford Overland",
        "Malibu Sedan",
        "Maverick",
        "Medford Steel",
        "Milford Pipe & Supply",
        "Milford Welding & Manufacturing Inc.",
        "Motorhome Chassis",
        "Mustang",
        "Mustang GTD",
        "Mustang Mach-E",
        "P600",
        "P700",
        "P800",
        "Probe",
        "RS200",
        "Ranger",
        "Ranger Raptor",
        "Raptor",
        "Recreational Vehicle",
        "Shelby GT350",
        "Shelby GT500",
        "Sierra Cosworth",
        "Stafford's Trailers",
        "Swinford Mfg",
        "Taurus",
        "Taurus X",
        "Tempo",
        "Thunderbird",
        "Transit",
        "Transit Connect",
        "Travel Park",
        "Waterford Tank and Fabrication, LTD",
        "Windstar",
        "ZX2"
    ],
    "Genesis": [
        "Envy",
        "G70",
        "G80",
        "G90",
        "GV60",
        "GV60 Magma",
        "GV70",
        "GV80",
        "Genesis",
        "Genesis Supreme",
        "Genesis Trailers Inc.",
        "Supreme",
        "Tahoe",
        "Vortex"
    ],
    "GMC": [
        "ACL",
        "ACM",
        "AT",
        "Acadia",
        "Aluminum Tilt",
        "Articulated Coach",
        "B7",
        "Bus Chassis",
        "C/K Pickup",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "CACL",
        "CNR",
        "CWG",
        "Caballero",
        "Canyon",
        "Cruise Origin AV",
        "Cutaway Chassis",
        "Cutaway Van",
        "D7",
        "DK",
        "DS",
        "Electric Vehicle",
        "Envoy",
        "FE",
        "Forward Control",
        "GMT-400",
        "Geo Tracker",
        "Heavy Conventional",
        "Hi-Cube",
        "Hummer EV",
        "Hummer EV Pickup",
        "Hummer EV SUV",
        "Jimmy",
        "Jimmy Utility",
        "Magna Van",
        "Motorhome Chassis",
        "NE",
        "NR",
        "P Truck Forward",
        "P6S",
        "R Conventional",
        "Rally",
        "S15 Pickup",
        "S15 Utility",
        "S6",
        "S7",
        "Safari",
        "Savana",
        "Sierra",
        "Sierra 1500",
        "Sierra 2500 HD",
        "Sierra 3500 HD",
        "Sierra HD",
        "Sierra Limited",
        "Sonoma",
        "Suburban",
        "Syclone",
        "T-Series",
        "Terrain",
        "Transit Coach",
        "Typhoon",
        "V Conventional",
        "Value Van",
        "Vandura",
        "W3",
        "W3500/W4500",
        "W4",
        "W5",
        "W5500/W5500 HD",
        "W6",
        "W7",
        "WB",
        "WCA",
        "WCL",
        "WCM",
        "WCS",
        "WHEB",
        "WHL",
        "WHLB",
        "WHM",
        "WHR",
        "WHS",
        "WIA",
        "WIL",
        "WIM",
        "WIS",
        "Yukon",
        "Yukon XL"
    ],
    "Hennessey": [
        "Venom F5",
        "Venom GT"
    ],
    "Honda": [
        "599",
        "919",
        "A1",
        "ADV150",
        "ADV160",
        "ATC250",
        "ATC350X",
        "Accord",
        "Accord Crosstour",
        "Africa Twin",
        "Africa Twin Adventure Sports",
        "Beat",
        "Big Red",
        "Big Ruckus",
        "CB-1",
        "CB1000 Hornet",
        "CB1000F",
        "CB1000R",
        "CB1100",
        "CB125",
        "CB250 (Nighthawk 250)",
        "CB300F",
        "CB300R",
        "CB450",
        "CB500",
        "CB500 Hornet",
        "CB500F",
        "CB500X",
        "CB50R",
        "CB550",
        "CB599",
        "CB650",
        "CB650F",
        "CB650R",
        "CB650RA",
        "CB700 (Nighthawk S)",
        "CB750",
        "CB750 (Nighthawk 750)",
        "CB900",
        "CB900 (Hornet)",
        "CBF1000",
        "CBF300",
        "CBF300N",
        "CBF600",
        "CBR1000F",
        "CBR1000RA",
        "CBR1000RR",
        "CBR1000S",
        "CBR1100X",
        "CBR125",
        "CBR125R",
        "CBR250",
        "CBR250R",
        "CBR250RA",
        "CBR300",
        "CBR300R",
        "CBR300RA",
        "CBR500",
        "CBR500R",
        "CBR500RA",
        "CBR600",
        "CBR600F",
        "CBR600RA",
        "CBR600RR",
        "CBR650",
        "CBR650F",
        "CBR650FA",
        "CBR650R",
        "CBR650RA",
        "CBR900/CBR954",
        "CBR900RR",
        "CBR929RR",
        "CBR954RR",
        "CBX",
        "CG150",
        "CG150ESD",
        "CH125",
        "CH150",
        "CH250",
        "CH80 (Elite)",
        "CHF50 (Jazz)",
        "CHF50 (Metropolitan)",
        "CHF50P (Metropolitan II)",
        "CM200",
        "CM250C",
        "CM400",
        "CM450",
        "CMX300",
        "CMX300 (Rebel 300)",
        "CMX450C",
        "CMX500 (Rebel 500)",
        "CN250",
        "CN250 (Helix)",
        "CR-V",
        "CR-X",
        "CR-Z",
        "CR125R",
        "CR250R",
        "CR500R",
        "CR80R",
        "CR85R",
        "CRF1000",
        "CRF1000 (Africa Twin)",
        "CRF1000A",
        "CRF1000A2",
        "CRF1000AS",
        "CRF1000ASD",
        "CRF1000D",
        "CRF1000D2",
        "CRF1000LA",
        "CRF1000LD",
        "CRF100F",
        "CRF110",
        "CRF1100 (Africa Twin)",
        "CRF11004",
        "CRF11004D",
        "CRF1100A",
        "CRF1100A4",
        "CRF1100D",
        "CRF1100D4",
        "CRF1100L",
        "CRF1100L4",
        "CRF1100L4D",
        "CRF1100LD",
        "CRF110F",
        "CRF125",
        "CRF125F",
        "CRF125FB",
        "CRF150",
        "CRF150F",
        "CRF150R",
        "CRF150RB",
        "CRF150RBE",
        "CRF150RE",
        "CRF230F",
        "CRF230L",
        "CRF230M",
        "CRF250",
        "CRF250F",
        "CRF250L",
        "CRF250LA",
        "CRF250R",
        "CRF250RB",
        "CRF250RL",
        "CRF250RLA",
        "CRF250RX",
        "CRF250X",
        "CRF300F",
        "CRF300L",
        "CRF450",
        "CRF450L",
        "CRF450R",
        "CRF450RB",
        "CRF450RL",
        "CRF450RWE",
        "CRF450RX",
        "CRF450X",
        "CRF50",
        "CRF50F",
        "CRF70F",
        "CRF80F",
        "CT70",
        "CTX1300",
        "CTX700",
        "CTX700N",
        "CX500",
        "CX650",
        "Civic",
        "Civic Si",
        "Civic Type R",
        "Clarity",
        "Cota",
        "Cota 300RR (MRT300)",
        "Cota 310RR",
        "Cota 4RT 260R",
        "Crosstour",
        "DAX125",
        "DN-01",
        "Del Sol",
        "ELITE 250",
        "ELITE 50",
        "ELITE 80",
        "EV Plus",
        "EZ90",
        "Element",
        "Elite",
        "Elite 110",
        "FCX Clarity",
        "Fireblade",
        "Fit",
        "Foreman",
        "Foreman Rubicon",
        "FourTrax",
        "FourTrax Foreman",
        "FourTrax Foreman Rubicon",
        "FourTrax Rancher",
        "FourTrax Recon",
        "FourTrax Rincon",
        "FourTrax Rubicon",
        "Fury",
        "GL1100 (GOLDWING)",
        "GL1200 (GOLDWING)",
        "GL1500A (GOLD WING ASPENCADE)",
        "GL1500C (VALKYRIE)",
        "GL1500CD (VALKYRIE TOURER)",
        "GL1500SE (GOLD WING SE)",
        "GL1800 (Goldwing)",
        "Giorno",
        "Gold Wing",
        "Gold Wing Interstate",
        "Gold Wing Tour",
        "Grom",
        "HR-V",
        "Hawk GT",
        "Helix",
        "Insight",
        "Integra Type R",
        "Interstate",
        "Jazz",
        "MRT260/COTA 4RT/4RT 260",
        "MRT260/COTA 4RT260",
        "MSX125 (Grom)",
        "Metropolitan",
        "Monkey",
        "Montesa Cota",
        "NB50 (Aero 50)",
        "NC50 (Express)",
        "NC700JD (NM4)",
        "NC700S",
        "NC700X",
        "NC750JD (NM4)",
        "NC750S",
        "NC750X",
        "NCH50 (Giorno)",
        "NCH50 (Metropolitan)",
        "NCW50 (Giorno)",
        "NCW50 (Metropolitan)",
        "NH80 (Aero 80)",
        "NN50 (Gyro)",
        "NPS50 (Ruckus)",
        "NQ50 (Spree)",
        "NRX1800 (Valkyrie Rune)",
        "NS50F",
        "NSR50MIN",
        "NSS250 (Reflex)",
        "NSS300 (Forza)",
        "NSX",
        "NT1100",
        "NT700V",
        "NU50 (Urban Express)",
        "NX125",
        "NX250",
        "NX500",
        "NX650",
        "Navi",
        "Odyssey",
        "PC800 (PACIFIC COAST)",
        "PCX",
        "PCX125",
        "PCX150",
        "Pacific Coast",
        "Passport",
        "Pilot",
        "Prelude",
        "Prologue",
        "RC 45",
        "RC213V",
        "RC30",
        "RC45",
        "RC51",
        "RVT1000R (RC51)",
        "Rancher",
        "Rebel",
        "Rebel 1100",
        "Rebel 300",
        "Rebel 500",
        "Recon",
        "Ridgeline",
        "Rincon",
        "Rubicon",
        "Ruckus",
        "S2000",
        "S660",
        "SA50",
        "SA50P",
        "SB50P",
        "SCL500",
        "SE50H",
        "SE50PH",
        "SE50PI",
        "SH150D/SH150i",
        "SH150i",
        "ST1100",
        "ST1100A",
        "ST1100AL",
        "ST1100L",
        "ST1100P",
        "ST1300",
        "ST1300A",
        "ST1300A/ST1300",
        "ST1300P",
        "ST1300PA",
        "SXS1000M (Pioneer 1000)",
        "SXS1000S (Talon 1000)",
        "SXS500M (Pioneer 500)",
        "SXS520M (Pioneer 520)",
        "SXS5M2 (Pioneer 520)",
        "SXS700M (Pioneer 700)",
        "Shadow",
        "Shadow Aero",
        "Shadow Phantom",
        "Silver Wing",
        "Silverwing",
        "Sport Tourer",
        "Sportrax",
        "Super Cub C125",
        "TG50 (Gyro S)",
        "TLR200",
        "TRX200D",
        "TRX200DN",
        "TRX250",
        "TRX250 (FourTrax 250)",
        "TRX250 (Recon)",
        "TRX250 (SportTrax 250)",
        "TRX250X",
        "TRX300",
        "TRX300EX",
        "TRX300EX (SportTrax 300)",
        "TRX300EXN",
        "TRX300FW",
        "TRX300FWN",
        "TRX300N",
        "TRX300X",
        "TRX350FE",
        "TRX350FE (FourTrax Rancher)",
        "TRX350FM",
        "TRX350FM (FourTrax Rancher)",
        "TRX350TE",
        "TRX350TE (FourTrax Rancher)",
        "TRX350TM",
        "TRX350TM (FourTrax Rancher)",
        "TRX400EX",
        "TRX400EX (SportTrax 400)",
        "TRX400FA",
        "TRX400FA (FourTrax Rancher AT)",
        "TRX400FG",
        "TRX400FG (FourTrax 400)",
        "TRX400FGA",
        "TRX400FGA (FourTrax Rancher AT)",
        "TRX400FW",
        "TRX400FW (FourTrax Foreman 400)",
        "TRX400FWN",
        "TRX400X",
        "TRX420",
        "TRX420 (Rancher)",
        "TRX450ER",
        "TRX450ER (SportTrax 450)",
        "TRX450ERB",
        "TRX450ERB (SportTrax 450)",
        "TRX450ES",
        "TRX450FE (FourTrax Foreman)",
        "TRX450FM",
        "TRX450FM (FourTrax Foreman)",
        "TRX450R",
        "TRX450R/TRX450ER",
        "TRX450S",
        "TRX500",
        "TRX500 (Foreman Rubicon)",
        "TRX500 (Foreman)",
        "TRX500 (FourTrax)",
        "TRX500 (Rubicon)",
        "TRX520",
        "TRX650FA (FourTrax Rincon)",
        "TRX650FA (Rincon)",
        "TRX650FG (Rincon)",
        "TRX650FGA (FourTrax Rincon)",
        "TRX680 (Rincon)",
        "TRX700 (Rubicon 700)",
        "TRX700EX",
        "TRX700XX",
        "TRX90 (Fourtrax 90)",
        "TRX90 (SportTrax 90)",
        "TRX90X",
        "Tourist Trophy",
        "Trail125",
        "Transalp",
        "VF1000F (Interceptor 1000)",
        "VF1000R",
        "VF1100 (Magna V65)",
        "VF1100 (Sabre V65)",
        "VF500 (Interceptor 500)",
        "VF500 (Magna V30)",
        "VF700 (Interceptor 700)",
        "VF700 (Magna V42)",
        "VF700 (Sabre V42)",
        "VF750 (Interceptor 750)",
        "VF750 (Magna V45)",
        "VF750 (Sabre V45)",
        "VFR1200F (Interceptor 1200)",
        "VFR1200X (Crosstourer)",
        "VFR750F",
        "VFR800 (Interceptor 800)",
        "VT1100 (Shadow 1100)",
        "VT1100 (Shadow Ace Tourer)",
        "VT1100 (Shadow Ace)",
        "VT1100 (Shadow Aero)",
        "VT1100 (Shadow Sabre)",
        "VT1100 (Shadow Spirit 1100)",
        "VT1300 (Fury)",
        "VT1300 (Interstate)",
        "VT1300 (Sabre)",
        "VT1300 (Stateline)",
        "VT500 (Ascot)",
        "VT500 (Shadow 500)",
        "VT600 (Shadow VLX Deluxe)",
        "VT600 (Shadow VLX)",
        "VT700 (Shadow 700)",
        "VT750 (Shadow Ace 750)",
        "VT750 (Shadow Aero 750)",
        "VT750 (Shadow Phantom 750)",
        "VT750 (Shadow RS 750)",
        "VT750 (Shadow Spirit 750)",
        "VT750 (Shadow Tourer)",
        "VT800 (Shadow 800)",
        "VTR1000F (Super Hawk)",
        "VTR250 (Interceptor 250)",
        "VTX1300",
        "VTX1800",
        "Valkyrie",
        "Valkyrie Interstate",
        "Valkyrie Tourer",
        "Varadero",
        "WW150/PCX150",
        "XL100S",
        "XL125",
        "XL200R",
        "XL250R",
        "XL350R",
        "XL500S",
        "XL600R",
        "XL600V",
        "XL80",
        "XR100R",
        "XR150L",
        "XR200",
        "XR200R",
        "XR250L",
        "XR250R",
        "XR350R",
        "XR400R",
        "XR500R",
        "XR50R",
        "XR600R",
        "XR650L",
        "XR650LL",
        "XR650R",
        "XR70R",
        "XR80R",
        "Z125 (Monkey)",
        "Z50R",
        "del Sol"
    ],
    "Hummer": [
        "H1",
        "H2",
        "H3",
        "H3T"
    ],
    "Hyundai": [
        "Accent",
        "Azera",
        "Elantra",
        "Elantra GT",
        "Elantra N",
        "Elantra Touring",
        "Entourage",
        "Equus",
        "Excel",
        "Genesis",
        "Genesis Coupe",
        "Hyundai Steel Industries, Inc.",
        "Hyundai Translead Trailers",
        "Ioniq",
        "Ioniq 5",
        "Ioniq 5 N",
        "Ioniq 6",
        "Ioniq 6 N",
        "Ioniq 9",
        "Kona",
        "Kona N",
        "Nexo",
        "Palisade",
        "Pony",
        "Santa Cruz",
        "Santa Fe",
        "Santa Fe Sport",
        "Santa Fe XL",
        "Scoupe",
        "Sonata",
        "Stellar",
        "Tiburon",
        "Tibur\u00f3n",
        "Tucson",
        "Veloster",
        "Veloster N",
        "Venue",
        "Veracruz",
        "XG300",
        "XG350",
        "Xcient"
    ],
    "Infiniti": [
        "EX35",
        "FX35",
        "FX37",
        "FX45",
        "FX50",
        "G20",
        "G25",
        "G35",
        "G37",
        "I30",
        "I35",
        "J30",
        "JX35",
        "M30",
        "M35",
        "M35h",
        "M37",
        "M45",
        "M56",
        "Q40",
        "Q45",
        "Q50",
        "Q60",
        "Q70",
        "Q70L",
        "QX30",
        "QX4",
        "QX50",
        "QX55",
        "QX56",
        "QX60",
        "QX65",
        "QX70",
        "QX80"
    ],
    "Jaguar": [
        "Black Jaguar",
        "E-PACE",
        "F-PACE",
        "F-TYPE",
        "I-PACE",
        "S-Type",
        "Vanden Plas",
        "X-Type",
        "XE",
        "XF",
        "XJ",
        "XJ12",
        "XJ220",
        "XJ6",
        "XJ8",
        "XJR",
        "XJS",
        "XK",
        "XK8"
    ],
    "Jeep": [
        "CJ-5",
        "CJ-6",
        "CJ-7",
        "CJ-8 Scrambler",
        "Cherokee",
        "Comanche",
        "Commander",
        "Compass",
        "Gladiator",
        "Grand Cherokee",
        "Grand Cherokee L",
        "Grand Wagoneer",
        "Grand Wagoneer L",
        "J-10",
        "J-20",
        "Jeepster",
        "Liberty",
        "Patriot",
        "Recon",
        "Renegade",
        "Wagoneer",
        "Wagoneer L",
        "Wagoneer S",
        "Wrangler",
        "Wrangler JK",
        "Wrangler Rubicon",
        "Wrangler Unlimited"
    ],
    "Karma": [
        "Atlantic",
        "GS-6",
        "Gyesera",
        "Karma",
        "Kaveya",
        "Revero",
        "Revero GT"
    ],
    "Kia": [
        "Amanti",
        "Borrego",
        "Cadenza",
        "Carnival",
        "EV3",
        "EV6",
        "EV9",
        "Forte",
        "Forte Koup",
        "K4",
        "K5",
        "K900",
        "Miami",
        "Niro",
        "Optima",
        "Rio",
        "Rondo",
        "Sedona",
        "Seltos",
        "Sephia",
        "Sorento",
        "Soul",
        "Spectra",
        "Sportage",
        "Stinger",
        "Tekiar",
        "Telluride"
    ],
    "Koenigsegg": [
        "Agera",
        "CC850",
        "CCX",
        "Gemera",
        "Jesko",
        "Koenigsegg Automotive",
        "One:1",
        "Regera"
    ],
    "Lamborghini": [
        "147",
        "Aventador",
        "Countach",
        "Diablo",
        "Gallardo",
        "Huracan",
        "Miura",
        "Murcielago",
        "Revuelto",
        "Roadster",
        "Temerario",
        "URUS",
        "Urus"
    ],
    "Land Rover": [
        "110\" WB",
        "88\u201d WB",
        "90\" WB",
        "Defender",
        "Defender 110",
        "Defender 130",
        "Defender 90",
        "Discovery",
        "Discovery Sport",
        "Freelander",
        "LR2",
        "LR3",
        "LR4",
        "New Range Rover",
        "Range Rover",
        "Range Rover Evoque",
        "Range Rover Sport",
        "Range Rover Velar"
    ],
    "Lexus": [
        "CT",
        "ES",
        "GS",
        "GS F",
        "GX",
        "HS",
        "IS",
        "IS F",
        "LC",
        "LFA",
        "LS",
        "LX",
        "NX",
        "RC",
        "RX",
        "RZ",
        "SC",
        "SC300",
        "SC400",
        "TX",
        "UX"
    ],
    "Lincoln": [
        "Aviator",
        "Blackwood",
        "Continental",
        "Corsair",
        "LS",
        "MKC",
        "MKS",
        "MKT",
        "MKX",
        "MKZ",
        "Mark",
        "Mark LT",
        "Nautilus",
        "Navigator",
        "Navigator L",
        "Town Car",
        "Zephyr"
    ],
    "Lotus": [
        "2-Eleven",
        "340R",
        "ELETRE",
        "Eagle",
        "Eclat",
        "Elan",
        "Eleven",
        "Elise",
        "Elite",
        "Emira",
        "Esprit",
        "Europa",
        "Evora",
        "Exige",
        "MEL",
        "Monaco",
        "Monza",
        "Spa",
        "Turbo Esprit"
    ],
    "Lucid": [
        "Air",
        "Gravity"
    ],
    "Maserati": [
        "228",
        "430",
        "Biturbo",
        "Coupe",
        "Ghibli",
        "GranTurismo",
        "Grancabrio",
        "Granturismo",
        "Grecale",
        "Levante",
        "MC20",
        "MCPura",
        "Merak",
        "Quattroporte",
        "Spyder",
        "TC"
    ],
    "Maybach": [
        "57",
        "62",
        "Exelero",
        "Zeppelin"
    ],
    "Mazda": [
        "323",
        "626",
        "929",
        "B-Series",
        "CX-3",
        "CX-30",
        "CX-5",
        "CX-50",
        "CX-7",
        "CX-70",
        "CX-9",
        "CX-90",
        "Cosmo",
        "GLC",
        "MPV",
        "MX-3",
        "MX-30",
        "MX-5",
        "MX-5 Miata",
        "MX-6",
        "Mazda2",
        "Mazda3",
        "Mazda5",
        "Mazda6",
        "Mazdaspeed3",
        "Mazdaspeed6",
        "Millenia",
        "Navajo",
        "Protege",
        "RX-7",
        "RX-7 FD",
        "RX-8",
        "Tribute"
    ],
    "McLaren": [
        "540C",
        "570GT",
        "570S",
        "600LT",
        "620R",
        "625C",
        "650S",
        "675LT",
        "720S",
        "750S",
        "765LT",
        "ARTURA",
        "Artura",
        "ELVA",
        "F1",
        "GT",
        "GTS",
        "Luggage Trailer",
        "MP4-12C",
        "P1",
        "SENNA",
        "SENNA GTR",
        "Senna"
    ],
    "Mercedes-Benz": [
        "190",
        "190E Evo II",
        "240",
        "260",
        "280",
        "300",
        "350",
        "380",
        "400",
        "420",
        "500",
        "560",
        "600",
        "A-Class",
        "AMG G63",
        "AMG GT",
        "B-Class",
        "C-Class",
        "CL-Class",
        "CLA",
        "CLA-Class",
        "CLE",
        "CLK-Class",
        "CLS",
        "CLS-Class",
        "E-Class",
        "EQB",
        "EQB-Class",
        "EQC-Class",
        "EQE",
        "EQE SUV",
        "EQE-Class SUV",
        "EQE-Class Sedan",
        "EQS",
        "EQS SUV",
        "EQS-Class SUV",
        "EQS-Class Sedan",
        "G-Class",
        "GL-Class",
        "GLA",
        "GLA-Class",
        "GLB",
        "GLB-Class",
        "GLC",
        "GLC-Class",
        "GLE",
        "GLE-Class",
        "GLK-Class",
        "GLS",
        "GLS-Class",
        "L1013",
        "L1113",
        "L1116",
        "L1117",
        "L1316",
        "L1317",
        "L1319",
        "L1418",
        "L1419",
        "LP1219",
        "LP1419",
        "LPS1525",
        "M-Class",
        "ML-Class",
        "Metris",
        "R-Class",
        "S-Class",
        "SL",
        "SL-Class",
        "SLC-Class",
        "SLK-Class",
        "SLR McLaren",
        "SLS AMG",
        "SLS-Class",
        "Sprinter",
        "Sprinter RV",
        "eSprinter"
    ],
    "Mercury": [
        "Capri",
        "Cougar",
        "Grand Marquis",
        "Lynx",
        "MARQUIS",
        "Marauder",
        "Mariner",
        "Milan",
        "Montego",
        "Monterey",
        "Mountaineer",
        "Mystique",
        "Sable",
        "Topaz",
        "Tracer",
        "Villager",
        "Zephyr"
    ],
    "Mini": [
        "Brockway Mini Homes",
        "Carolina Trikes & Minis",
        "Clubman",
        "Cooper",
        "Cooper Convertible",
        "Cooper Countryman",
        "Cooper Coupe",
        "Cooper Roadster",
        "Countryman",
        "Delta Waseca Mini",
        "Dominight LLC",
        "Dominion Motorcycle",
        "FL",
        "GEMINI AUTO & TRAILER INC",
        "Hardtop",
        "KW",
        "Los Lobos Mini Choppers, LLC",
        "MINI MONSOON",
        "Mack",
        "Miller",
        "MiniKamp",
        "MiniMixx",
        "Minitears Company",
        "Mobile Frac Storage Tank",
        "Mobile Mini Inc.",
        "My Mini Trailer LLC.",
        "ODB Trailer",
        "Paceman",
        "Pete",
        "Pony",
        "R.V. Mini Mart, Inc.",
        "Santa Barbara"
    ],
    "Mitsubishi": [
        "3000GT",
        "Cordia",
        "Delica",
        "Diamante",
        "Eclipse",
        "Eclipse Cross",
        "Eclipse GSX",
        "Endeavor",
        "Expo",
        "FE140 (FECZTS)",
        "FE160 (FEC7TS)",
        "FE160 (FEC7TW)",
        "FE180 (FEC9TS)",
        "FE434",
        "FE439",
        "FE444",
        "FE449",
        "FE639",
        "FE640",
        "FE640DW",
        "FE649",
        "FE83D",
        "FE84D",
        "FE84DW",
        "FE85D",
        "FEC52S",
        "FEC72S",
        "FEC72W",
        "FEC7US / eCanter",
        "FEC92S",
        "FECX2S",
        "FG434",
        "FG439",
        "FG639",
        "FG649",
        "FG84D",
        "FGB72S",
        "FH100",
        "FH210",
        "FH211",
        "FK415",
        "FK417",
        "FK455",
        "FK457",
        "FK617",
        "FK61F",
        "FK62F",
        "FK65F",
        "FM555",
        "FM557",
        "FM617",
        "FM61F",
        "FM64F",
        "FM657",
        "FM65F",
        "Galant",
        "Lancer",
        "Lancer Evo",
        "Lancer Evolution",
        "Lancer SportBack",
        "Low Speed Vehicle",
        "Mighty Max",
        "Mirage",
        "Mirage G4",
        "Montero",
        "Montero Sport",
        "Outlander",
        "Outlander Sport",
        "Pajero",
        "Precis",
        "RVR",
        "Raider",
        "SP",
        "SPX",
        "Sigma",
        "Space Wagon",
        "Starion",
        "Sterling 360",
        "Tredia",
        "Truck",
        "Van",
        "Wagon",
        "i-MiEV"
    ],
    "Nissan": [
        "180SX",
        "200SX",
        "240SX",
        "300ZX",
        "350Z",
        "370Z",
        "Altima",
        "Altra",
        "Altra-EV",
        "Ariya",
        "Ariya Hatchback",
        "Ariya MPV",
        "Armada",
        "Axxess",
        "Cube",
        "Fairlady Z",
        "Frontier",
        "GT-R",
        "Juke",
        "Kicks",
        "Kicks MPV",
        "Kicks Play",
        "Leaf",
        "Maxima",
        "Micra",
        "Murano",
        "NV",
        "NV200",
        "NX",
        "Nissan Z",
        "PULSAR",
        "Pathfinder",
        "Pickup",
        "Pulsar GTI-R",
        "Quest",
        "Rogue",
        "Rogue Select",
        "Rogue Sport",
        "S13",
        "S14",
        "S15",
        "Sentra",
        "Sentra Classic",
        "Silvia",
        "Skyline",
        "Skyline GT-R",
        "Stagea",
        "Stanza",
        "Stanza Wagon",
        "Titan",
        "Van",
        "Versa",
        "Versa Note",
        "X-Trail",
        "Xterra",
        "Z"
    ],
    "Noble": [
        "M500",
        "M600",
        "Nobles, Inc Trailer",
        "Tim Nobles Trailers"
    ],
    "Oldsmobile": [
        "442",
        "Achieva",
        "Alero",
        "Aurora",
        "Bravada",
        "Custom Cruiser",
        "Cutlass",
        "Cutlass Calais",
        "Cutlass Ciera",
        "Cutlass Cruiser",
        "Cutlass Salon",
        "Cutlass Supreme",
        "Delta 88",
        "Eighty Eight (88)",
        "Firenza",
        "Intrigue",
        "LSS",
        "Ninety Eight (98)",
        "Omega",
        "Regency",
        "Silhouette",
        "Toronado"
    ],
    "Pagani": [
        "Huayra",
        "Utopia",
        "Zonda"
    ],
    "Polestar": [
        "1",
        "2",
        "3",
        "4",
        "Polestar 1",
        "Polestar 2",
        "Polestar 3",
        "Polestar 4",
        "Polestar 5",
        "Polestar Trailers, Inc."
    ],
    "Pontiac": [
        "6000",
        "Acadian",
        "Aztek",
        "Bonneville",
        "Catalina",
        "Fiero",
        "Firebird",
        "Firefly",
        "G3",
        "G5",
        "G6",
        "G8",
        "GTO",
        "Grand AM",
        "Grand Am",
        "Grand Lemans",
        "Grand Prix",
        "J2000",
        "Laurentian",
        "Lemans",
        "Matiz",
        "Montana",
        "Montana SV6",
        "Parisienne",
        "Phoenix",
        "Pursuit",
        "Safari",
        "Solstice",
        "Sunbird",
        "Sunbird 2000",
        "Sunburst",
        "Sunfire",
        "T1000",
        "Tempest",
        "Torrent",
        "Trans Am",
        "Trans Sport",
        "Vibe",
        "Wave"
    ],
    "Porsche": [
        "718 Boxster",
        "718 Cayman",
        "718 Spyder",
        "911",
        "911 GT3",
        "911 GT3 RS",
        "911 Turbo",
        "918",
        "918 Spyder",
        "924",
        "928",
        "944",
        "959",
        "968",
        "Boxster",
        "Carrera GT",
        "Cayenne",
        "Cayman",
        "Macan",
        "Macan EV",
        "Panamera",
        "Taycan",
        "Taycan Cross Turismo"
    ],
    "Ram": [
        "1000",
        "1225U",
        "1500",
        "166U",
        "2000",
        "203",
        "206U",
        "214",
        "2235",
        "234",
        "2500",
        "2600",
        "266",
        "288",
        "3000",
        "307",
        "3500",
        "3510",
        "3600",
        "4000",
        "4500",
        "512",
        "52",
        "5500",
        "612U",
        "625U",
        "62U",
        "725",
        "825U",
        "83",
        "835",
        "83U",
        "925",
        "B17 Bomber",
        "B29 Super Fortress",
        "Best Lane Enterprises dba Ramp Free",
        "Brammo Street Bikes",
        "Burkett's Autorama",
        "CP102B",
        "CP80B",
        "CP90B",
        "Cargo Van",
        "Chopper",
        "Cruiser",
        "Dual Sport",
        "EZR",
        "EZTRJ",
        "EZWR",
        "Easton Custom L.L.C",
        "EnduraMax",
        "FATT HOGG FRAMES",
        "FRAMTRAC MANUFACTURING CO. LTD",
        "Faith",
        "Framar",
        "HX-1000",
        "HX-2000",
        "HX-3000",
        "Holiday Rambler",
        "JR RAMIRO",
        "JSR",
        "John Ingram, Inc.",
        "KTM Aluminum Frame",
        "KTM Steel Frame",
        "Kramo Trailers",
        "LXR",
        "Metro Tram",
        "NEXGEN FRAMING SYSTEM, LLC",
        "P38 Lightning",
        "P40 Warhawk",
        "P47 Thunderbird",
        "P51 Mustang",
        "P63 King Cobra",
        "Paramount Custom Cycles",
        "PortAFrame",
        "ProMaster",
        "ProMaster 1500",
        "ProMaster 2500",
        "ProMaster 3500",
        "ProMaster City",
        "Promaster City",
        "Protorype",
        "Pyramid Manufacturing Co. Trailer",
        "RAMP AGE TRAILER CO.",
        "RAMSA",
        "RAMSHORN WELDING",
        "ROAD TRAMPS MC",
        "Ram Enterprises, LLC",
        "Ram Fabrication",
        "Ram Transcorp",
        "Rambler",
        "Ramika Industries Trailer",
        "Ramirez Trailer",
        "Ramp Champ",
        "Rampless",
        "Rampless Motorcycle Trailers",
        "Ramptek Trailers",
        "Ramsey Fabrication",
        "Replica",
        "Robert Allen Mowery Ramco LLC",
        "SCHRAMM, INC.",
        "Scooter",
        "TRX",
        "TerraMarc Industries",
        "Touring",
        "Tram Power Car",
        "Tram Trailer",
        "Tramont Corporation",
        "Tramont Manufacturing LLC",
        "Urban",
        "WVR",
        "YWR",
        "YWVR"
    ],
    "Rimac": [
        "Concept One",
        "Nevera",
        "Nevera R"
    ],
    "Rivian": [
        "EDV",
        "R1S",
        "R1T",
        "R2",
        "RCV"
    ],
    "Rolls-Royce": [
        "Camargue",
        "Corniche",
        "Cullinan",
        "Dawn",
        "Flying Spur",
        "Ghost",
        "Park Ward",
        "Phantom",
        "Silver Dawn",
        "Silver Seraph",
        "Silver Shadow",
        "Silver Spirit",
        "Silver Spur",
        "Spectre",
        "Touring Limousine",
        "Wraith"
    ],
    "Saab": [
        "9-2X",
        "9-3",
        "9-4x",
        "9-5",
        "9-7X",
        "900",
        "900 Turbo",
        "9000"
    ],
    "Saleen": [
        "S1",
        "S5S Raptor",
        "S7"
    ],
    "Saturn": [
        "Astra",
        "Aura",
        "Ion",
        "Ion Redline",
        "L200",
        "L300",
        "LS",
        "LS1",
        "LS2",
        "LW1",
        "LW2",
        "LW200",
        "LW300",
        "Outlook",
        "Relay",
        "SATURN2016",
        "SATURN2019",
        "SC1",
        "SC2",
        "SL",
        "SL1",
        "SL2",
        "SL3",
        "SW1",
        "SW2",
        "Saturn Industries",
        "Sky",
        "Vue"
    ],
    "Scion": [
        "FR-S",
        "iA",
        "iM",
        "tC",
        "xB",
        "xD"
    ],
    "Smart": [
        "Beverage Industry",
        "Catering / Food Industry",
        "Construction Industry",
        "EQ Fortwo",
        "EQ fortwo",
        "Elyx Smart",
        "Fortwo",
        "Fortwo Electric Drive",
        "Open Platform",
        "SMART MANUFACTURING",
        "SMART TRAILERS, INC.",
        "SMART TRANSPORT SOLUTIONS",
        "Smart Trailer",
        "Smart Trailers",
        "SmartFeed",
        "Street Smart Performance",
        "Tiny SMART House",
        "Tow Smart",
        "fortwo",
        "smart"
    ],
    "Spyker": [
        "C12",
        "C8",
        "D8/D12"
    ],
    "Subaru": [
        "Ascent",
        "B9 Tribeca",
        "BRZ",
        "Baja",
        "Brat",
        "Crosstrek",
        "DL",
        "Forester",
        "GL",
        "GL-10",
        "GLF",
        "Impreza",
        "Impreza WRX STI",
        "Justy",
        "Legacy",
        "Loyale",
        "Outback",
        "RX",
        "SVX",
        "Sambar",
        "Solterra",
        "Standard",
        "Trailseeker",
        "Uncharted",
        "WRX",
        "WRX STI",
        "XT",
        "XT6",
        "XV CrossTrek"
    ],
    "Suzuki": [
        "AN400",
        "AN400 / AN400S",
        "AN400A",
        "AN400AL",
        "AN400K",
        "AN400L",
        "AN650",
        "AN650A",
        "AN650AL",
        "AN650K",
        "AN650L",
        "Aerio",
        "Bandit 1250S",
        "Boulevard",
        "Boulevard C50 (VL800L9) / Boulevard C50T (VL800TL9)",
        "Boulevard C50(VL800L8) / Boulevard C50T(VL800TL8)",
        "Boulevard C50T",
        "Boulevard C90 B.O.S.S. (VL1500BL8)  / Boulevard C90T(VL1500TL8)",
        "Boulevard C90 B.O.S.S. (VL1500BL9) / Boulevard C90T (VL1500TL9)",
        "Boulevard M109R B.O.S.S. (VZR1800BZL9)",
        "Boulevard M109R B.O.S.S.(VZR1800BZL8)",
        "Boulevard M50 (VZ800L9)",
        "Boulevard M50(VZ800L8)",
        "Boulevard M90 (VZ1500L9)",
        "Boulevard M90(VZ1500L8)",
        "Boulevard S40 (LS650BL9)",
        "Boulevard S40(LS650BL8 )",
        "Burgman 200",
        "Burgman 400",
        "Burgman 650",
        "Business",
        "Cappuccino",
        "DL1000",
        "DL1000A/DL1000AA",
        "DL1000AL/DL1000AAL",
        "DL1000K",
        "DL1000L",
        "DL1000XAAL9 (V-Strom 1000XT Adventure)",
        "DL1050",
        "DL650",
        "DL650A",
        "DL650AAL/DL650AL",
        "DL650AL",
        "DL650K",
        "DL650L",
        "DL650XA/DL650A",
        "DL650XAAL9 (V-Strom 650XT Touring)",
        "DL650XAL/DL650AAL/DL650AL",
        "DL650XAL7",
        "DR-Z110",
        "DR-Z110K",
        "DR-Z125",
        "DR-Z125K",
        "DR-Z125L",
        "DR-Z125LK",
        "DR-Z125LL",
        "DR-Z125LL/DR-Z125L",
        "DR-Z12LM",
        "DR-Z250",
        "DR-Z250K",
        "DR-Z400",
        "DR-Z400E",
        "DR-Z400EK",
        "DR-Z400K",
        "DR-Z400S",
        "DR-Z400SK",
        "DR-Z400SL",
        "DR-Z400SL8",
        "DR-Z400SL9",
        "DR-Z400SM",
        "DR-Z400SML",
        "DR-Z400SML8",
        "DR-Z400SML9",
        "DR-Z4S",
        "DR-Z50",
        "DR-Z70",
        "DR125SE",
        "DR200S",
        "DR200SE",
        "DR200SEK",
        "DR200SEL",
        "DR200SL",
        "DR200SL8",
        "DR200SL9",
        "DR250F",
        "DR250SE",
        "DR350",
        "DR350SE",
        "DR650S",
        "DR650SE",
        "DR650SEK",
        "DR650SEL",
        "DR650SEL8",
        "DR650SEL9",
        "DS80",
        "Enduro",
        "Equator",
        "Esteem",
        "Family",
        "Forenza",
        "Forsa",
        "GN125E",
        "GN125E/ GN125ET",
        "GS1150",
        "GS450",
        "GS500",
        "GS500(GS500H)/GS500F(GS500FH)",
        "GS500E",
        "GS500E/GS500ET",
        "GS500FK",
        "GS500K",
        "GS550L",
        "GS700E",
        "GS750",
        "GSF1200",
        "GSF1200S",
        "GSF1200S/GSF1200SZ",
        "GSF1200S/SA",
        "GSF1200SK",
        "GSF1200SK/GSF1200K",
        "GSF1250SA",
        "GSF1250SA/GSX1250SA",
        "GSF400",
        "GSF600S",
        "GSF600S/GSF600ST",
        "GSF600SK",
        "GSF650S",
        "GSF650SA",
        "GSX",
        "GSX-8R",
        "GSX-8S",
        "GSX-8T",
        "GSX-8TT",
        "GSX-R1000",
        "GSX-R1000AL",
        "GSX-R1000K",
        "GSX-R1000L",
        "GSX-R1000R",
        "GSX-R1100",
        "GSX-R1100W",
        "GSX-R600",
        "GSX-R600K",
        "GSX-R600L",
        "GSX-R600W",
        "GSX-R750",
        "GSX-R750K",
        "GSX-R750L",
        "GSX-R750W",
        "GSX-S1000",
        "GSX-S1000A",
        "GSX-S1000AL7",
        "GSX-S1000AL8 / GSX-S1000ZAL8",
        "GSX-S1000AL9/GSXS1000ZAL9/GSXS1000YAL9",
        "GSX-S1000F",
        "GSX-S1000FA",
        "GSX-S1000FAL7",
        "GSX-S1000FAL8",
        "GSX-S1000GT+",
        "GSX-S1000GT/GSX-S1000GT+",
        "GSX-S750",
        "GSX-S750L8",
        "GSX-S750ZAL8 / GSX-S750L8",
        "GSX-S750ZL/GSX-S750L",
        "GSX-S750ZL9 (49st)",
        "GSX-Z750ZAL9 (50st) / GSX-S750YAL9 (50st) / GSX-S750ZL9 (50st)",
        "GSX1100",
        "GSX1100G",
        "GSX1250FA",
        "GSX1250FAL",
        "GSX1300 RK5",
        "GSX1300BK",
        "GSX1300BKA",
        "GSX1300R",
        "GSX1300RAL",
        "GSX1300RAL/GSX1300RAZL",
        "GSX1300RAL9 (Hayabusa)",
        "GSX1300RAM0 (Hayabusa)",
        "GSX1300RK",
        "GSX1300RL",
        "GSX1300RL/GSX1300RZL",
        "GSX1300RRM2 / GSX1300RRZM2",
        "GSX250R",
        "GSX600F",
        "GSX600F/GSX600FT",
        "GSX600FK",
        "GSX650F",
        "GSX650FA",
        "GSX750F",
        "GSX750F/GSX750FT",
        "GSX750FK",
        "GSXS1000FZL9",
        "GSXS1000SM0",
        "GSXS1000SM1",
        "GV1200GL",
        "GV1400",
        "GV700GL",
        "GW250/GW250F/GW250Z",
        "GW250FL/GW250ZL",
        "GW250L",
        "GZ250",
        "GZ250K",
        "Grand Vitara",
        "Grand Vitara XL-7",
        "Hayabusa",
        "Hayabusa(GSX1300RAL8)",
        "JR50",
        "JR50K",
        "JR80",
        "JR80K",
        "Jimny",
        "Katana",
        "KingQuad",
        "Kizashi",
        "LS650",
        "LS650BL7",
        "LS650L",
        "LS650P",
        "LS650PK",
        "LT-A400",
        "LT-A400F/LT-A400FC/LT-A400FH",
        "LT-A400F/LT-A400FZ",
        "LT-A400FK",
        "LT-A400K",
        "LT-A450X",
        "LT-A50",
        "LT-A500",
        "LT-A500F",
        "LT-A500F/LT-A500FC",
        "LT-A500FK",
        "LT-F160",
        "LT-F250",
        "LT-F250F",
        "LT-F250FK",
        "LT-F250K",
        "LT-F250L",
        "LT-F300F",
        "LT-F400",
        "LT-F400F",
        "LT-F400F/LT-F400FC",
        "LT-F400FK",
        "LT-F400FU",
        "LT-F400K",
        "LT-F4WD",
        "LT-F4WDX",
        "LT-F500F",
        "LT-F500F/QUADRUNNER",
        "LT-F500FK",
        "LT-R450",
        "LT-R450/LT-R450Z",
        "LT-R450Z",
        "LT-V700F",
        "LT-Z250",
        "LT-Z250/ LT-Z250Z",
        "LT-Z250K",
        "LT-Z400/LT-Z400Z",
        "LT-Z400K",
        "LT-Z400L",
        "LT-Z400L/LT-Z400ZL",
        "LT-Z400Z",
        "LT-Z50",
        "LT-Z50/LT-Z50Z",
        "LT-Z50L",
        "LT-Z90",
        "LT-Z90L",
        "LT-Z90L/QuadSport Z90",
        "LT160K",
        "LT80",
        "LT80K",
        "Leisure",
        "Low Speed Vehicle",
        "Mini-Leisure",
        "Moto-Cross",
        "Off Road Play",
        "QUV620F",
        "RF600R",
        "RF900R",
        "RM-Z250",
        "RM-Z250K",
        "RM-Z250L",
        "RM-Z450",
        "RM-Z450L",
        "RM100",
        "RM100K",
        "RM125",
        "RM125K",
        "RM125T",
        "RM250",
        "RM250/ RM250T",
        "RM250K",
        "RM60",
        "RM60K",
        "RM65",
        "RM65K",
        "RM80",
        "RM80T",
        "RM85",
        "RM85K",
        "RM85L",
        "RM85LK",
        "RM85LL",
        "RMX250",
        "RMX450",
        "RMX450ZL",
        "RV200L7",
        "RV200L8",
        "RV200L9",
        "Reno",
        "SFV650",
        "SFV650A",
        "SFV650L",
        "SP200",
        "SP600",
        "SV1000 / SV1000S",
        "SV1000K / SV1000SK",
        "SV1000S",
        "SV650",
        "SV650/SV650S",
        "SV650/SV650S/SV650SF",
        "SV650A/SV650SA",
        "SV650A/SV650SA/SV650SAF",
        "SV650AL7",
        "SV650AL8",
        "SV650AL9 / SV650XAL9",
        "SV650K/SV650SK",
        "SV650L7",
        "SV650L8",
        "SV650L9",
        "SX4",
        "Samurai",
        "Sidekick",
        "Sidekick Sport",
        "Suzuki Boulevard M109R B.O.S.S.",
        "Swift",
        "TL1000R",
        "TL1000RK",
        "TL1000S",
        "TU250X",
        "TU250XL",
        "TU250XL8",
        "TU250XL9",
        "Touring",
        "UH200AL",
        "UH200AM2",
        "UH200L",
        "UZ125C",
        "V-Strom 1000 ABS(DL1000AL8) / V-Strom 1000 XT ABS(DL100XAL8)",
        "V-Strom 1050",
        "V-Strom 1050XT",
        "V-Strom 650",
        "V-Strom 650XT",
        "V-Strom 650XT Adventure",
        "V-Strom 800",
        "V-Strom 800DE / V-Strom 800DE Adventure",
        "VL1500",
        "VL1500 / VL1500T",
        "VL1500BL/VL1500TL",
        "VL1500K",
        "VL1500L/VL1500BL/VL1500TL/VL1500BTL",
        "VL800",
        "VL800 / VL800T / VL800C/VL800B",
        "VL800/VL800C/VL800T",
        "VL800/VL800T/VL800Z",
        "VL800BL/VL800CL/VL800L/VL800TL",
        "VL800CL/VL800L/VL800TL",
        "VL800K",
        "VL800L/VL800TL",
        "VL800TL",
        "VLR1800/VLR1800T",
        "VS1400",
        "VS1400/VS1400GL",
        "VS1400GLP",
        "VS1400GLPK",
        "VS700",
        "VS750 Intruder",
        "VS800",
        "VS800GL",
        "VS800GLK",
        "VX800",
        "VZ1500",
        "VZ1500L",
        "VZ1600",
        "VZ1600K",
        "VZ800",
        "VZ800/VZ800B/VZ800Z",
        "VZ800/VZ800Z",
        "VZ800K",
        "VZ800L",
        "VZR1800",
        "VZR1800/VZR1800Z",
        "VZR1800/VZR1800Z/VZR1800N",
        "VZR1800BZL",
        "VZR1800BZL/VZR1800L/VZR1800ZL",
        "VZR1800L/VZR1800ZL",
        "Verona",
        "Vitara",
        "X-90",
        "XL7"
    ],
    "Tesla": [
        "Cybercab",
        "Cybertruck",
        "Model 3",
        "Model S",
        "Model X",
        "Model Y",
        "Roadster",
        "Semi"
    ],
    "Toyota": [
        "4Runner",
        "86",
        "AE86",
        "Avalon",
        "C-HR",
        "COROLLA iM",
        "Camry",
        "Camry Solara",
        "Cargo Van",
        "Celica",
        "Century",
        "Chaser",
        "Corolla",
        "Corolla Cross",
        "Corolla Matrix",
        "Corona",
        "Cressida",
        "Crown",
        "Crown Signia",
        "Echo",
        "FCHV-adv",
        "FJ Cruiser",
        "GR Corolla",
        "GR86",
        "Grand Highlander",
        "Highlander",
        "Land Cruiser",
        "MR2",
        "Mirai",
        "Paseo",
        "Pick-Up",
        "Previa",
        "Prius",
        "Prius C",
        "Prius Prime (PHEV)",
        "Prius V",
        "RAV4",
        "RAV4 Prime (PHEV)",
        "Scion FR-S",
        "Scion iA",
        "Scion iM",
        "Scion iQ",
        "Scion tC",
        "Scion xA",
        "Scion xB",
        "Scion xD",
        "Sequoia",
        "Sienna",
        "Sprinter Trueno",
        "Starlet",
        "Supra",
        "T100",
        "Tacoma",
        "Tercel",
        "Tundra",
        "Van",
        "Venza",
        "Yaris",
        "Yaris iA",
        "bZ",
        "bZ Woodland",
        "bZ4X"
    ],
    "VinFast": [
        "VF 6",
        "VF 7",
        "VF 8",
        "VF 9"
    ],
    "Volkswagen": [
        "Arteon",
        "Atlas",
        "Atlas Cross Sport",
        "Beetle",
        "CABRIOLET",
        "CC",
        "Cabrio",
        "Corrado",
        "Dasher",
        "Eos",
        "EuroVan",
        "FOX",
        "GLI",
        "GTI",
        "Golf",
        "Golf Alltrack",
        "Golf GTI",
        "Golf III",
        "Golf R",
        "Golf SportWagen",
        "ID. Buzz",
        "ID.4",
        "ID.Buzz",
        "Jetta",
        "Jetta GLI",
        "Jetta SportWagen",
        "Jetta Wagon",
        "KOMBI",
        "Karmann Ghia",
        "Passat",
        "Phaeton",
        "Quantum",
        "R32",
        "Rabbit",
        "Routan",
        "Scirocco",
        "Taos",
        "Tiguan",
        "Tiguan Limited",
        "Touareg",
        "Vanagon",
        "e-Golf"
    ],
    "Volvo": [
        "240",
        "240 Series",
        "260 Series",
        "740 Series",
        "760 Series",
        "780 Series",
        "850 Series",
        "850 T-5R",
        "940 Series",
        "960 Series",
        "9700",
        "ACL",
        "B10M",
        "B12B",
        "B12M",
        "B12R",
        "B13R",
        "B5R",
        "B5TL",
        "B7R",
        "B8L",
        "B8R",
        "B9L",
        "B9R",
        "B9S",
        "B9TL",
        "BE",
        "BFE",
        "BRH",
        "BRLH",
        "BXR",
        "BXRB",
        "BXXR",
        "C30",
        "C40",
        "C40 Recharge",
        "C70",
        "C70 / C30",
        "CACL",
        "CNE",
        "CNR",
        "CWG",
        "Cab Behind Engine",
        "Cab Over Engine HT",
        "Cab Over Engine LT",
        "EC40",
        "EX30",
        "EX30 CC",
        "EX40",
        "EX60",
        "EX90",
        "F12 w/F7 Cab",
        "F6 w/F7 Cab",
        "FE",
        "FM10",
        "FML",
        "NE",
        "NE42",
        "NE64",
        "NR",
        "NR64",
        "S40",
        "S60",
        "S60 Cross Country",
        "S70",
        "S80",
        "S90",
        "V40",
        "V50",
        "V60",
        "V60CC",
        "V70",
        "V90",
        "V90CC",
        "VAH",
        "VHD",
        "VN",
        "VNC",
        "VNL",
        "VNL (4)",
        "VNM",
        "VNR",
        "VNR (4)",
        "VNX",
        "VS",
        "VT",
        "Volvo Trailers",
        "WAH",
        "WCA",
        "WG",
        "WHEB",
        "WHL",
        "WHLB",
        "WHR",
        "WIA",
        "WX",
        "WXLL",
        "WXLM",
        "WXR",
        "XC40",
        "XC60",
        "XC70",
        "XC90"
    ]
};
